#!/usr/bin/env bash
# Configure Nginx to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
if grep -q "nginx is not running" <(service nginx status); then service nginx stop; fi
